---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/enarha/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-test-for-docker-images
